'use client';

interface VerificationDetailsProps {
  result: {
    txHash: string;
    blockNumber: number;
    generationId?: string;
    selectionId?: string;
  };
  walletAddress: string;
  customResult?: string; // For displaying custom results like YOLO/NO WAY
  allItems?: string[]; // For displaying all items that were in the selection
}

export default function VerificationDetails({ result, walletAddress, customResult, allItems }: VerificationDetailsProps) {
  const copyToClipboard = async (text: string) => {
    try {
      await navigator.clipboard.writeText(text);
    } catch (error) {
      console.error('Failed to copy to clipboard:', error);
    }
  };

  const getShareableUrl = () => {
    const baseUrl = window.location.origin;
    const params = new URLSearchParams({
      verify: 'true',
      tx: result.txHash
    });
    return `${baseUrl}?${params.toString()}`;
  };

  const openFlowscan = () => {
    const url = `https://evm-testnet.flowscan.io/tx/${result.txHash}`;
    window.open(url, '_blank', 'noopener,noreferrer');
  };

  return (
    <div className="mt-6">
      <div className="relative group">
        <div className="absolute -inset-0.5 bg-gradient-to-r from-neon-green to-neon-blue rounded-xl blur opacity-30 group-hover:opacity-50 transition duration-1000"></div>
        <div className="relative bg-black/50 rounded-xl p-6 border border-neon-green/20 space-y-4 overflow-hidden">
          <h3 className="font-press-start text-sm text-neon-green flex items-center gap-2">
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
            </svg>
            Verification Details
          </h3>
          
          <div className="space-y-3 text-sm">
            <div>
              <span className="text-neon-pink">Transaction Hash:</span>
              <div className="mt-1 flex items-start gap-2">
                <code className="text-neon-blue break-all text-xs bg-black/50 px-2 py-1 rounded flex-1 min-w-0">
                  {result.txHash}
                </code>
                <button
                  onClick={() => copyToClipboard(result.txHash)}
                  className="text-neon-purple hover:text-neon-pink transition-colors p-1"
                  title="Copy hash"
                >
                  <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                  </svg>
                </button>
              </div>
            </div>
            
            <div>
              <span className="text-neon-pink">Block Number:</span>
              <span className="text-white ml-2">{result.blockNumber}</span>
            </div>

            <div>
              <span className="text-neon-pink">Generated By:</span>
              <div className="mt-1">
                <code className="text-white text-xs bg-black/50 px-2 py-1 rounded break-all block">
                  {walletAddress}
                </code>
              </div>
            </div>

            {(result.generationId || result.selectionId) && (
              <div>
                <span className="text-neon-pink">Generation ID:</span>
                <div className="mt-1 flex items-start gap-2">
                  <code className="text-neon-blue break-all text-xs bg-black/50 px-2 py-1 rounded flex-1 min-w-0 word-wrap">
                    {result.generationId || result.selectionId}
                  </code>
                  <button
                    onClick={() => copyToClipboard(result.generationId || result.selectionId || '')}
                    className="text-neon-purple hover:text-neon-pink transition-colors p-1 flex-shrink-0"
                    title="Copy ID"
                  >
                    <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                    </svg>
                  </button>
                </div>
              </div>
            )}
          </div>

          {/* Action buttons */}
          <div className="pt-4 border-t border-white/10 space-y-3">
            <h4 className="font-press-start text-xs text-neon-purple">Share & Verify</h4>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              <button
                onClick={openFlowscan}
                className="relative group"
              >
                <div className="absolute -inset-0.5 bg-gradient-to-r from-neon-blue to-neon-green rounded-lg blur opacity-50 group-hover:opacity-75 transition duration-1000"></div>
                <div className="relative px-4 py-2 bg-black rounded-lg flex items-center justify-center gap-2 font-press-start text-xs text-white group-hover:text-neon-blue transition-all duration-300">
                  <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                  </svg>
                  View on Flowscan
                </div>
              </button>
              
              <button
                onClick={() => copyToClipboard(getShareableUrl())}
                className="relative group"
              >
                <div className="absolute -inset-0.5 bg-gradient-to-r from-neon-purple to-neon-pink rounded-lg blur opacity-50 group-hover:opacity-75 transition duration-1000"></div>
                <div className="relative px-4 py-2 bg-black rounded-lg flex items-center justify-center gap-2 font-press-start text-xs text-white group-hover:text-neon-pink transition-all duration-300">
                  <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                  </svg>
                  Copy Share Link
                </div>
              </button>
            </div>
          </div>

          {/* Custom result section */}
          {customResult && (
            <div className="pt-4 border-t border-white/10">
              <div>
                <span className="text-neon-pink">Result:</span>
                <span className="text-neon-green ml-2 font-press-start text-sm">{customResult}</span>
              </div>
            </div>
          )}

          {/* All items section for lists */}
          {allItems && allItems.length > 0 && (
            <div className="pt-4 border-t border-white/10">
              <div>
                <span className="text-neon-pink">All Items ({allItems.length}):</span>
                <div className="mt-2 max-h-32 overflow-y-auto">
                  <div className="text-xs text-white space-y-1">
                    {allItems.map((item, index) => (
                      <div key={index} className="flex items-start gap-2">
                        <span className="text-neon-purple flex-shrink-0">{index + 1}.</span>
                        <span className="break-all">{item}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* Info section */}
          <div className="pt-4 border-t border-white/10">
            <div className="text-xs text-neon-green space-y-1">
              <div>✓ Random value generated using Flow VRF</div>
              <div>✓ Transaction recorded on Flow blockchain</div>
              <div>✓ Verifiable by anyone with the transaction hash</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}